core/urls.py
from django.conf.urls import include, url
from core.views import *
from django.contrib.auth import views as auth_views
from core import views as core_views



urlpatterns = [

    url(r'^$', core_views.index, name='index'),
    # for our home/index page
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^search_list/$', SearchList.as_view(), name='search_list'),
    url(r'^(?P<short_id>\w{6})$', redirect_original, name='redirectoriginal'),
    # when short URL is requested it redirects to original URL
    url(r'^makeshort/$', shorten_url, name='shortenurl'),
    # this will create a URL's short id and return the short URL
    ]

urlshortener/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from core import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls',  namespace='core')),

]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class Urls(models.Model):
    short_id = models.SlugField(max_length=6,primary_key=True)
    httpurl = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)

    user = models.ForeignKey(User, null=True)
    search_fields = ('short_id', 'httpurl', 'pub_date')

    class Meta:
        verbose_name = 'Url'
        verbose_name_plural = 'Urls'

def __str__(self):
    return self.httpurl

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
import random, string, json
from core.models import Urls
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.contrib.auth import login, logout, authenticate
from core.forms import SignUpForm
from django.views.generic import ListView
from django.contrib.sites.shortcuts import get_current_site


def index(request):
    return render(request, 'index.html')


def signup(request):
    if request.method == 'POST'or None:
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('core:index')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


class SearchList(ListView):
    template_name = 'search_list.html'
    model = Urls
    context_object = 'url'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Urls.objects.all()
        return Urls.objects.filter(user=self.request.user)



def redirect_original(request, short_id):
    url = get_object_or_404(Urls, pk=short_id) # get object, if not found return 404 error
    url.count += 1
    url.save()
    print(url.httpurl)
    return HttpResponseRedirect(url.httpurl)


def shorten_url(request):
    current_site = get_current_site(request)
    current_site.domain
    url = request.POST.get("url", '')
    if not (url == ''):
        short_id = get_short_code()
        b = Urls(httpurl=url, short_id=short_id, user=request.user)
        b.save()

        response_data = {}
        # response_data['url'] = settings.SITE_URL + "/" + short_id
        response_data['url'] = current_site.domain + "/" + short_id
    return HttpResponse(json.dumps(response_data),  content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")


def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = Urls.objects.get(pk=short_id)
        except:
            return short_id

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Grow | Welcome to mysite{% endblock %}</title>

    <!--Custom Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!--image background-->
    <link rel="shortcut icon" href="{% static 'img/banner-bg.jpg' %}">

    <!--Bootstrap core CSS-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/contact-input-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/hover-effect.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.dataTables.min.css' %}" rel="stylesheet">
  </head>
<!-- NAVBAR
================================================== -->
<body>

<nav class="navbar navbar-default top-bar affix" data-spy="affix" data-offset-top="250" >
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
          <button data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" class="navbar-toggle" type="button">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'core:index' %}">GROW</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
				      {% if user.is_authenticated %}
                 <li><a href="{% url 'core:logout' %}">LOGOUT</a></li>
                 <li><a href="">Welcome, {{ user }}!</a></li>
                 <li><a href="{% url 'core:search_list' %}">Search List Url</a></li>
            </ul>
               {% else %}
                   <li><a href="{% url 'core:login' %}">LOGIN</a></li>
                   <li><a href="{% url 'core:signup' %}">SIGN UP</a></li>
               {% endif %}
      </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <script src="{% static 'js/oppear_1.1.2.min.js' %}"></script>

    <script type="text/javascript">
       $(function() {
           $('#submitButton').click(function() {
               $.ajax({
                   type: "POST",
                   url: "/makeshort/",
                   data: {
                       'url': $('#url').val(),
                       'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                   },
                   success: returnSuccess,
                   dataType: 'json'
               });
           });

        $(document).ready(function() {
           $('#short_id').DataTable( {
             "order": [[ 1, "desc" ]]

               } );
          } );
       });

       function returnSuccess(data, textStatus, jqXHR) {
           if (data.url) {
               $('#url-result').text(data.url);
               $('#url').val("");
           } else {
               $('#url-result').text("Do not submit blank.");
           }
       }
    </script>
    {% block container %}

    {% endblock %}
  </body>
</html>

core/templates/index.html
{% extends "base.html" %}

{% block title %}Grow - Make your URL shorter!{% endblock %}

{% block container %}
<section class="banner-sec" id="home">
    <div class="container">
      <div class="col-md-12 col-sm-12 col-xs-12 jumbotron">
          <h1>Perfection is not attainable</h1>
          <h2>but if we chase perfection we can catch excellence</h2>
            <div class="input-group">
                <input type="text" class="form-control" name="url" id="url" placeholder="Pasta a link to shorten it">
                  <span class="input-group-btn">
                    {% csrf_token %}
                  <button id="submitButton" class="btn btn-search">SHORTEN</button>
                  </span>
            </div>

            <div class="container">
                  <span id="url-result">Enter the URL above and click submit!</span>
            </div>
      </div>
    </div>


{% endblock %}

core/templates/search_list.html
{% extends 'base.html' %}

{% block container %}

<section class="banner-sec" id="home">
    <div class="container">
        <h2>List of shortened urls</h2>
        <table id="short_id" class="display" width="100%" cellspacing="0">
          <thead>
               <tr>
                   <th>Short Id</th>
                   <th>Url</th>

               </tr>
           </thead>
           <tfoot>
               <tr>
                 <th>Short Id</th>
                 <th>Url</th>
               </tr>
           </tfoot>


                {% for url in object_list %}
                        <tr>
                                <td>{{ url.short_id }}</td>
                                <td>{{ url.httpurl }}</td>

                        </tr>
                {% empty %}
                        <li>No items in the list.</li>
                {% endfor %}
          </table>


    </div>
{% endblock container %}